/**
 * icon.js — decorative mask icons, with optional raw (background-image) mode.
 * icon(name) returns a <span class="icon" data-icon="name">. Colour comes from CSS
 * (background-color: currentColor) and the glyph from a CSS mask keyed on [data-icon]
 * (see assets/icons/icons.css, generated by tools/build-icon-sprite.mjs). No theme
 * subscription is needed — currentColor follows the theme automatically.
 *
 * Pass { raw: true } for icons that carry their own colour/opacity (e.g. accent chart
 * thumbnails). These get the .icon--raw class and render via background-image instead
 * of a mask; theme-swapped via [data-theme] overrides of --icon (see icons.css and
 * tools/build-icon-sprite.mjs ACCENT baking).
 */

/**
 * @param {string} name
 * @param {{cls?:string, raw?:boolean}} [opts]
 *   raw: render the baked SVG as a background-image (non-masked), for icons that
 *   carry their own colour/opacity (e.g. accent thumbnails). See .icon--raw in
 *   css/components.css and the raw-icon support in tools/build-icon-sprite.mjs.
 * @returns {HTMLSpanElement}
 */
export function icon(name, opts = {}) {
  const el = document.createElement('span');
  const cls = ['icon'];
  if (opts.raw) cls.push('icon--raw');
  if (opts.cls) cls.push(opts.cls);
  el.className = cls.join(' ');
  el.setAttribute('data-icon', name);
  el.setAttribute('aria-hidden', 'true');
  return el;
}
