/**
 * D.Mike — Unit Converter Data (unit-data.js)
 * All unit categories, conversion functions, and reference values.
 * Separated from module logic for maintainability.
 */

export const CATEGORIES = {
  laenge: {
    nameKey: 'catLength', icon: 'unit.length',
    units: {
      nm:  { nameKey: 'nm',  toBase: v => v * 1e-9,       fromBase: v => v / 1e-9 },
      um:  { nameKey: 'um',  toBase: v => v * 1e-6,       fromBase: v => v / 1e-6 },
      mil: { nameKey: 'mil', toBase: v => v * 2.54e-5,    fromBase: v => v / 2.54e-5 },
      mm:  { nameKey: 'mm',  toBase: v => v * 1e-3,       fromBase: v => v / 1e-3 },
      cm:  { nameKey: 'cm',  toBase: v => v * 1e-2,       fromBase: v => v / 1e-2 },
      m:   { nameKey: 'm',   toBase: v => v,              fromBase: v => v },
      km:  { nameKey: 'km',  toBase: v => v * 1e3,        fromBase: v => v / 1e3 },
      in:  { nameKey: 'in',  toBase: v => v * 0.0254,     fromBase: v => v / 0.0254 },
      ft:  { nameKey: 'ft',  toBase: v => v * 0.3048,     fromBase: v => v / 0.3048 },
      yd:  { nameKey: 'yd',  toBase: v => v * 0.9144,     fromBase: v => v / 0.9144 },
      mi:  { nameKey: 'mi',  toBase: v => v * 1609.344,   fromBase: v => v / 1609.344 },
    },
    refs: [[1,'mil','um'],[1,'mil','mm'],[10,'mil','mm'],[1,'in','mil'],[1,'in','mm'],[1,'ft','cm'],[1,'mi','km']],
  },
  flaeche: {
    nameKey: 'catArea', icon: 'unit.area',
    units: {
      mm2: { nameKey: 'mm2', toBase: v => v * 1e-6,      fromBase: v => v / 1e-6 },
      cm2: { nameKey: 'cm2', toBase: v => v * 1e-4,      fromBase: v => v / 1e-4 },
      m2:  { nameKey: 'm2',  toBase: v => v,              fromBase: v => v },
      ar:  { nameKey: 'ar',  toBase: v => v * 100,        fromBase: v => v / 100 },
      ha:  { nameKey: 'ha',  toBase: v => v * 1e4,        fromBase: v => v / 1e4 },
      km2: { nameKey: 'km2', toBase: v => v * 1e6,        fromBase: v => v / 1e6 },
      in2: { nameKey: 'in2', toBase: v => v * 6.4516e-4,  fromBase: v => v / 6.4516e-4 },
      ft2: { nameKey: 'ft2', toBase: v => v * 0.092903,   fromBase: v => v / 0.092903 },
      ac:  { nameKey: 'ac',  toBase: v => v * 4046.856,   fromBase: v => v / 4046.856 },
    },
    refs: [[1,'ar','m2'],[1,'ha','ar'],[1,'ha','m2'],[1,'ac','m2'],[1,'km2','ha'],[1,'ft2','m2']],
  },
  volumen: {
    nameKey: 'catVolume', icon: 'unit.volume',
    units: {
      mm3:  { nameKey: 'mm3',  toBase: v => v * 1e-9,           fromBase: v => v / 1e-9 },
      cm3:  { nameKey: 'cm3',  toBase: v => v * 1e-6,           fromBase: v => v / 1e-6 },
      ml:   { nameKey: 'ml',   toBase: v => v * 1e-6,           fromBase: v => v / 1e-6 },
      cl:   { nameKey: 'cl',   toBase: v => v * 1e-5,           fromBase: v => v / 1e-5 },
      l:    { nameKey: 'l',    toBase: v => v * 1e-3,           fromBase: v => v / 1e-3 },
      m3:   { nameKey: 'm3',   toBase: v => v,                  fromBase: v => v },
      gal:  { nameKey: 'gal',  toBase: v => v * 0.003785411784, fromBase: v => v / 0.003785411784 },
      floz: { nameKey: 'floz', toBase: v => v * 2.957353e-5,    fromBase: v => v / 2.957353e-5 },
    },
    refs: [[1,'l','ml'],[1,'l','cm3'],[1,'gal','l'],[1,'m3','l'],[1,'l','floz']],
  },
  masse: {
    nameKey: 'catMass', icon: 'unit.mass',
    units: {
      mg: { nameKey: 'mg', toBase: v => v * 1e-6,     fromBase: v => v / 1e-6 },
      g:  { nameKey: 'g',  toBase: v => v * 1e-3,     fromBase: v => v / 1e-3 },
      kg: { nameKey: 'kg', toBase: v => v,             fromBase: v => v },
      t:  { nameKey: 't',  toBase: v => v * 1e3,       fromBase: v => v / 1e3 },
      oz: { nameKey: 'oz', toBase: v => v * 0.0283495, fromBase: v => v / 0.0283495 },
      lb: { nameKey: 'lb', toBase: v => v * 0.453592,  fromBase: v => v / 0.453592 },
    },
    refs: [[1,'kg','lb'],[1,'oz','g'],[1,'t','kg'],[1,'lb','g']],
  },
  druck: {
    nameKey: 'catPressure', icon: 'unit.pressure',
    units: {
      Pa:   { nameKey: 'Pa',   toBase: v => v,            fromBase: v => v },
      hPa:  { nameKey: 'hPa',  toBase: v => v * 100,      fromBase: v => v / 100 },
      kPa:  { nameKey: 'kPa',  toBase: v => v * 1e3,      fromBase: v => v / 1e3 },
      MPa:  { nameKey: 'MPa',  toBase: v => v * 1e6,      fromBase: v => v / 1e6 },
      bar:  { nameKey: 'bar',  toBase: v => v * 1e5,      fromBase: v => v / 1e5 },
      mbar: { nameKey: 'mbar', toBase: v => v * 100,      fromBase: v => v / 100 },
      atm:  { nameKey: 'atm',  toBase: v => v * 101325,   fromBase: v => v / 101325 },
      psi:  { nameKey: 'psi',  toBase: v => v * 6894.757, fromBase: v => v / 6894.757 },
      mmHg: { nameKey: 'mmHg', toBase: v => v * 133.322,  fromBase: v => v / 133.322 },
    },
    refs: [[1,'bar','Pa'],[1,'atm','bar'],[1,'psi','kPa'],[1013.25,'hPa','atm']],
  },
  temperatur: {
    nameKey: 'catTemperature', icon: 'unit.temperature',
    units: {
      C: { nameKey: 'C', toBase: v => v,                fromBase: v => v },
      F: { nameKey: 'F', toBase: v => (v - 32) * 5 / 9, fromBase: v => v * 9 / 5 + 32 },
      K: { nameKey: 'K', toBase: v => v - 273.15,        fromBase: v => v + 273.15 },
    },
    refs: [[0,'C','F'],[100,'C','F'],[0,'C','K'],[212,'F','C']],
  },
  kraft: {
    nameKey: 'catForce', icon: 'unit.force',
    units: {
      N:   { nameKey: 'N',   toBase: v => v,             fromBase: v => v },
      kN:  { nameKey: 'kN',  toBase: v => v * 1e3,       fromBase: v => v / 1e3 },
      lbf: { nameKey: 'lbf', toBase: v => v * 4.44822,   fromBase: v => v / 4.44822 },
      kgf: { nameKey: 'kgf', toBase: v => v * 9.80665,   fromBase: v => v / 9.80665 },
      dyn: { nameKey: 'dyn', toBase: v => v * 1e-5,       fromBase: v => v / 1e-5 },
    },
    refs: [[1,'kN','N'],[1,'lbf','N'],[1,'kgf','N'],[1e5,'dyn','N']],
  },
  drehmoment: {
    nameKey: 'catTorque', icon: 'unit.torque',
    units: {
      Nm:    { nameKey: 'Nm',    toBase: v => v,            fromBase: v => v },
      kNm:   { nameKey: 'kNm',   toBase: v => v * 1e3,      fromBase: v => v / 1e3 },
      lbfft: { nameKey: 'lbfft', toBase: v => v * 1.35582,  fromBase: v => v / 1.35582 },
      kgfm:  { nameKey: 'kgfm',  toBase: v => v * 9.80665,  fromBase: v => v / 9.80665 },
    },
    refs: [[1,'Nm','lbfft'],[100,'Nm','kgfm'],[1,'kNm','Nm'],[1,'lbfft','Nm']],
  },
  energie: {
    nameKey: 'catEnergy', icon: 'unit.energy',
    units: {
      J:    { nameKey: 'J',    toBase: v => v,           fromBase: v => v },
      kJ:   { nameKey: 'kJ',   toBase: v => v * 1e3,     fromBase: v => v / 1e3 },
      cal:  { nameKey: 'cal',  toBase: v => v * 4.184,   fromBase: v => v / 4.184 },
      kcal: { nameKey: 'kcal', toBase: v => v * 4184,    fromBase: v => v / 4184 },
      Wh:   { nameKey: 'Wh',   toBase: v => v * 3600,    fromBase: v => v / 3600 },
      kWh:  { nameKey: 'kWh',  toBase: v => v * 3.6e6,   fromBase: v => v / 3.6e6 },
      BTU:  { nameKey: 'BTU',  toBase: v => v * 1055.06, fromBase: v => v / 1055.06 },
    },
    refs: [[1,'kWh','kJ'],[1,'kcal','kJ'],[1,'BTU','J'],[1,'kJ','Wh']],
  },
  leistung: {
    nameKey: 'catPower', icon: 'unit.power',
    units: {
      uW:   { nameKey: 'uW',   toBase: v => v * 1e-6,                    fromBase: v => v * 1e6 },
      mW:   { nameKey: 'mW',   toBase: v => v * 1e-3,                    fromBase: v => v * 1e3 },
      W:    { nameKey: 'W',    toBase: v => v,                            fromBase: v => v },
      kW:   { nameKey: 'kW',   toBase: v => v * 1e3,                     fromBase: v => v / 1e3 },
      MW:   { nameKey: 'MW',   toBase: v => v * 1e6,                     fromBase: v => v / 1e6 },
      PS:   { nameKey: 'PS',   toBase: v => v * 735.499,                 fromBase: v => v / 735.499 },
      hp:   { nameKey: 'hp',   toBase: v => v * 745.7,                   fromBase: v => v / 745.7 },
      BTUh: { nameKey: 'BTUh', toBase: v => v * 0.29307,                 fromBase: v => v / 0.29307 },
      dBm:  { nameKey: 'dBm',  toBase: v => Math.pow(10, v / 10) * 1e-3, fromBase: v => 10 * Math.log10(v * 1e3) },
      dBW:  { nameKey: 'dBW',  toBase: v => Math.pow(10, v / 10),         fromBase: v => 10 * Math.log10(v) },
    },
    refs: [[1,'kW','PS'],[1,'hp','kW'],[0,'dBm','mW'],[10,'dBm','mW'],[20,'dBm','W'],[30,'dBm','W'],[0,'dBW','W'],[1,'W','dBm']],
  },
  durchfluss: {
    nameKey: 'catFlowRate', icon: 'unit.flow-rate',
    units: {
      lmin: { nameKey: 'lmin', toBase: v => v,                fromBase: v => v },
      lh:   { nameKey: 'lh',   toBase: v => v / 60,           fromBase: v => v * 60 },
      m3h:  { nameKey: 'm3h',  toBase: v => v * 1000 / 60,    fromBase: v => v * 60 / 1000 },
      m3s:  { nameKey: 'm3s',  toBase: v => v * 1000 * 60,    fromBase: v => v / (1000 * 60) },
      gpm:  { nameKey: 'gpm',  toBase: v => v * 3.78541,      fromBase: v => v / 3.78541 },
    },
    refs: [[1,'lmin','lh'],[1,'m3h','lmin'],[1,'gpm','lmin'],[60,'lmin','m3h']],
  },
  geschwindigkeit: {
    nameKey: 'catSpeed', icon: 'unit.speed',
    units: {
      ms:   { nameKey: 'ms',   toBase: v => v,              fromBase: v => v },
      kmh:  { nameKey: 'kmh',  toBase: v => v / 3.6,        fromBase: v => v * 3.6 },
      mph:  { nameKey: 'mph',  toBase: v => v * 0.44704,    fromBase: v => v / 0.44704 },
      fts:  { nameKey: 'fts',  toBase: v => v * 0.3048,     fromBase: v => v / 0.3048 },
      kn:   { nameKey: 'kn',   toBase: v => v * 0.51444,    fromBase: v => v / 0.51444 },
      mach: { nameKey: 'mach', toBase: v => v * 343,        fromBase: v => v / 343 },
      c:    { nameKey: 'c',    toBase: v => v * 299792458,   fromBase: v => v / 299792458 },
    },
    refs: [[100,'kmh','ms'],[1,'mph','kmh'],[1,'kn','kmh'],[1,'mach','kmh'],[1,'c','kmh'],[1,'c','ms']],
  },
  zeit: {
    nameKey: 'catTime', icon: 'unit.time',
    units: {
      ms_t: { nameKey: 'ms_t', toBase: v => v * 0.001,  fromBase: v => v / 0.001 },
      s:    { nameKey: 's',    toBase: v => v,            fromBase: v => v },
      min:  { nameKey: 'min',  toBase: v => v * 60,       fromBase: v => v / 60 },
      h:    { nameKey: 'h',    toBase: v => v * 3600,     fromBase: v => v / 3600 },
      d:    { nameKey: 'd',    toBase: v => v * 86400,    fromBase: v => v / 86400 },
      wo:   { nameKey: 'wo',   toBase: v => v * 604800,   fromBase: v => v / 604800 },
      iMin: { nameKey: 'iMin', toBase: v => v * 36,       fromBase: v => v / 36 },
      iSek: { nameKey: 'iSek', toBase: v => v * 0.36,     fromBase: v => v / 0.36 },
      iStd: { nameKey: 'iStd', toBase: v => v * 3600,     fromBase: v => v / 3600 },
      cmin: { nameKey: 'cmin', toBase: v => v * 36,       fromBase: v => v / 36 },
    },
    refs: [[1,'h','iMin'],[45,'min','iMin'],[30,'iMin','min'],[100,'iMin','min'],[1,'iStd','min'],[8,'h','iMin']],
  },
  winkel: {
    nameKey: 'catAngle', icon: 'unit.angle',
    units: {
      deg:  { nameKey: 'deg',  toBase: v => v,                     fromBase: v => v },
      rad:  { nameKey: 'rad',  toBase: v => v * (180 / Math.PI),    fromBase: v => v * (Math.PI / 180) },
      gon:  { nameKey: 'gon',  toBase: v => v * 0.9,               fromBase: v => v / 0.9 },
      amin: { nameKey: 'amin', toBase: v => v / 60,                fromBase: v => v * 60 },
      asec: { nameKey: 'asec', toBase: v => v / 3600,              fromBase: v => v * 3600 },
      rev:  { nameKey: 'rev',  toBase: v => v * 360,               fromBase: v => v / 360 },
    },
    refs: [[180,'deg','rad'],[360,'deg','gon'],[1,'rev','deg'],[90,'deg','rad']],
  },
  drehzahl: {
    nameKey: 'catRPM', icon: 'unit.rpm',
    units: {
      rpm:  { nameKey: 'rpm',  toBase: v => v,                              fromBase: v => v },
      rps:  { nameKey: 'rps',  toBase: v => v * 60,                         fromBase: v => v / 60 },
      radS: { nameKey: 'radS', toBase: v => v * (60 / (2 * Math.PI)),       fromBase: v => v * (2 * Math.PI) / 60 },
      degS: { nameKey: 'degS', toBase: v => v / 6,                          fromBase: v => v * 6 },
      Hz:   { nameKey: 'Hz',   toBase: v => v * 60,                         fromBase: v => v / 60 },
    },
    refs: [[1,'rpm','rps'],[1,'Hz','rpm'],[1500,'rpm','radS'],[3000,'rpm','Hz']],
  },
  ph: {
    nameKey: 'catPH', icon: 'unit.ph',
    units: {
      pH:    { nameKey: 'pH',    toBase: v => Math.pow(10, -v),         fromBase: v => -Math.log10(v) },
      pOH:   { nameKey: 'pOH',   toBase: v => Math.pow(10, -(14 - v)), fromBase: v => 14 + Math.log10(v) },
      Hmol:  { nameKey: 'Hmol',  toBase: v => v,                        fromBase: v => v },
      Hmmol: { nameKey: 'Hmmol', toBase: v => v * 1e-3,                 fromBase: v => v * 1e3 },
      Humol: { nameKey: 'Humol', toBase: v => v * 1e-6,                 fromBase: v => v * 1e6 },
      OHmol: { nameKey: 'OHmol', toBase: v => 1e-14 / v,               fromBase: v => 1e-14 / v },
    },
    refs: [[0,'pH','Hmol'],[7,'pH','Hmol'],[7,'pH','pOH'],[14,'pH','Hmol'],[2,'pH','Hmmol'],[1,'pH','OHmol']],
  },
  konzentration: {
    nameKey: 'catConcentration', icon: 'unit.concentration',
    units: {
      mgl:  { nameKey: 'mgl',  toBase: v => v,        fromBase: v => v },
      ugl:  { nameKey: 'ugl',  toBase: v => v * 1e-3, fromBase: v => v * 1e3 },
      ngl:  { nameKey: 'ngl',  toBase: v => v * 1e-6, fromBase: v => v * 1e6 },
      gl:   { nameKey: 'gl',   toBase: v => v * 1e3,  fromBase: v => v / 1e3 },
      kgl:  { nameKey: 'kgl',  toBase: v => v * 1e6,  fromBase: v => v / 1e6 },
      ppm:  { nameKey: 'ppm',  toBase: v => v,        fromBase: v => v },
      ppb:  { nameKey: 'ppb',  toBase: v => v * 1e-3, fromBase: v => v * 1e3 },
      ppt:  { nameKey: 'ppt',  toBase: v => v * 1e-6, fromBase: v => v * 1e6 },
      proz: { nameKey: 'proz', toBase: v => v * 1e4,  fromBase: v => v / 1e4 },
      prom: { nameKey: 'prom', toBase: v => v * 1e3,  fromBase: v => v / 1e3 },
      mgkg: { nameKey: 'mgkg', toBase: v => v,        fromBase: v => v },
    },
    refs: [[1,'ppm','mgl'],[1,'ppb','ugl'],[1,'proz','ppm'],[1,'prom','ppm'],[1,'gl','ppm'],[1000,'ppm','proz']],
  },
  schall: {
    nameKey: 'catSound', icon: 'unit.sound',
    units: {
      dBSPL: { nameKey: 'dBSPL', toBase: v => 2e-5 * Math.pow(10, v / 20), fromBase: v => 20 * Math.log10(v / 2e-5) },
      Pa_s:  { nameKey: 'Pa_s',  toBase: v => v,                            fromBase: v => v },
      uPa:   { nameKey: 'uPa',   toBase: v => v * 1e-6,                     fromBase: v => v * 1e6 },
      mPa:   { nameKey: 'mPa_s', toBase: v => v * 1e-3,                     fromBase: v => v * 1e3 },
    },
    refs: [[0,'dBSPL','uPa'],[20,'dBSPL','uPa'],[60,'dBSPL','Pa_s'],[85,'dBSPL','Pa_s'],[120,'dBSPL','Pa_s'],[140,'dBSPL','Pa_s']],
  },
  laborwerte: {
    nameKey: 'catLabValues', icon: 'unit.lab-values',
    groups: {
      'bloodSugar':  ['mgdl_bz','mmoll_bz','gl_bz','mgml_bz'],
      'cholesterol': ['mgdl_ch','mmoll_ch','gl_ch'],
      'creatinine':  ['mgdl_kr','umoll_kr','mgl_kr','gl_kr'],
      'hba1c':       ['proz_hb','mmolmol_hb','eag_mgdl','eag_mmoll'],
    },
    units: {
      mgdl_bz:    { nameKey: 'mgdl',      toBase: v => v,                     fromBase: v => v },
      mmoll_bz:   { nameKey: 'mmoll',     toBase: v => v * 18.02,            fromBase: v => v / 18.02 },
      gl_bz:      { nameKey: 'gl',        toBase: v => v * 100,              fromBase: v => v / 100 },
      mgml_bz:    { nameKey: 'mgml',      toBase: v => v * 100,              fromBase: v => v / 100 },
      mgdl_ch:    { nameKey: 'mgdl',      toBase: v => v,                     fromBase: v => v },
      mmoll_ch:   { nameKey: 'mmoll',     toBase: v => v * 38.67,            fromBase: v => v / 38.67 },
      gl_ch:      { nameKey: 'gl',        toBase: v => v * 100,              fromBase: v => v / 100 },
      mgdl_kr:    { nameKey: 'mgdl',      toBase: v => v,                     fromBase: v => v },
      umoll_kr:   { nameKey: 'umoll',     toBase: v => v / 88.4,             fromBase: v => v * 88.4 },
      mgl_kr:     { nameKey: 'mgl_lab',   toBase: v => v / 10,               fromBase: v => v * 10 },
      gl_kr:      { nameKey: 'gl',        toBase: v => v * 100,              fromBase: v => v / 100 },
      proz_hb:    { nameKey: 'prozNGSP',  toBase: v => v,                     fromBase: v => v },
      mmolmol_hb: { nameKey: 'mmolmolIFCC', toBase: v => v / 10.929 + 2.15,  fromBase: v => (v - 2.15) * 10.929 },
      eag_mgdl:   { nameKey: 'eag_mgdl',  toBase: v => (v + 46.7) / 28.7,    fromBase: v => 28.7 * v - 46.7 },
      eag_mmoll:  { nameKey: 'eag_mmoll', toBase: v => (v + 2.5944) / 1.5944, fromBase: v => 1.5944 * v - 2.5944 },
    },
    refs: [
      [100,'mgdl_bz','mmoll_bz'],[126,'mgdl_bz','mmoll_bz'],[200,'mgdl_bz','mmoll_bz'],
      [200,'mgdl_ch','mmoll_ch'],[240,'mgdl_ch','mmoll_ch'],
      [1.0,'mgdl_kr','umoll_kr'],[1.2,'mgdl_kr','umoll_kr'],
      [6.5,'proz_hb','mmolmol_hb'],[7.0,'proz_hb','eag_mgdl'],
    ],
  },
};

export const TIMEZONES = [
  { labelKey: 'tzUTC',          tz: 'UTC' },
  { labelKey: 'tzBerlin',      tz: 'Europe/Berlin' },
  { labelKey: 'tzVienna',      tz: 'Europe/Vienna' },
  { labelKey: 'tzZurich',      tz: 'Europe/Zurich' },
  { labelKey: 'tzLondon',      tz: 'Europe/London' },
  { labelKey: 'tzParis',       tz: 'Europe/Paris' },
  { labelKey: 'tzMoscow',      tz: 'Europe/Moscow' },
  { labelKey: 'tzIstanbul',    tz: 'Europe/Istanbul' },
  { labelKey: 'tzDubai',       tz: 'Asia/Dubai' },
  { labelKey: 'tzIndia',       tz: 'Asia/Kolkata' },
  { labelKey: 'tzBangkok',     tz: 'Asia/Bangkok' },
  { labelKey: 'tzSingapore',   tz: 'Asia/Singapore' },
  { labelKey: 'tzShanghai',    tz: 'Asia/Shanghai' },
  { labelKey: 'tzTokyo',       tz: 'Asia/Tokyo' },
  { labelKey: 'tzSeoul',       tz: 'Asia/Seoul' },
  { labelKey: 'tzSydney',      tz: 'Australia/Sydney' },
  { labelKey: 'tzAuckland',    tz: 'Pacific/Auckland' },
  { labelKey: 'tzNewYork',     tz: 'America/New_York' },
  { labelKey: 'tzChicago',     tz: 'America/Chicago' },
  { labelKey: 'tzDenver',      tz: 'America/Denver' },
  { labelKey: 'tzLosAngeles',  tz: 'America/Los_Angeles' },
  { labelKey: 'tzMexicoCity',  tz: 'America/Mexico_City' },
  { labelKey: 'tzSaoPaulo',    tz: 'America/Sao_Paulo' },
];

export const TZ_WORLD_CLOCK_INDICES = [0, 1, 4, 17, 20, 13, 15];
