#!/usr/bin/env node
/**
 * build-templates — inline every js/ ** / *.html template into index.html as
 * <template data-tpl="<relpath>"> blocks, so the engine can clone() them
 * (sink-free) instead of fetch()+DOMParser. Zero dependencies.
 *
 *   node tools/build-templates/build.mjs           # rewrite index.html in place
 *   node tools/build-templates/build.mjs --check   # exit 1 if index.html stale
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { readdirSync, statSync } from 'node:fs';
import { join, relative, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
export const KEY_PREFIX = 'js/';
const START = '<!-- TEMPLATES:START (generated by tools/build-templates) -->';
const END = '<!-- TEMPLATES:END -->';

/**
 * Shared markup blocks live next to the code they belong to and end in
 * `.part.html`. They are never emitted as templates of their own — they only
 * exist to be inlined into real templates via the `@include` directive.
 * @param {string} key template key, e.g. 'js/core/flowchart/substeps.part.html'
 * @returns {boolean}
 */
export function isPartial(key) {
  return key.endsWith('.part.html');
}

/**
 * Matches `<!-- @include js/path/to/file.part.html -->` on a line of its own,
 * capturing its indentation. One directive per line: the indentation is what
 * lets the inlined block keep the host template's shape.
 */
const INCLUDE_RE = /^([ \t]*)<!--\s*@include\s+(\S+?)\s*-->[ \t]*$/gm;
/** Same pattern, non-global — `.test()` on a /g/ regex is stateful. */
const HAS_INCLUDE_RE = /^[ \t]*<!--\s*@include\s+\S+?\s*-->[ \t]*$/m;
/** A partial's leading doc comment — for developers reading the file, not for shipping. */
const LEADING_COMMENT_RE = /^\s*<!--[\s\S]*?-->\s*/;

/**
 * Replace every `@include` directive with the referenced partial's content.
 *
 * Alpine CSP has no component or partial mechanism of its own, so a block
 * that four module templates share (the substeps disclosure) would otherwise
 * be copy-pasted four times and drift. Resolving it here keeps one source of
 * truth without changing anything at runtime — the engine still clones a
 * fully inlined <template>.
 *
 * Includes are NOT resolved recursively: a partial including a partial would
 * invite cycles for no current benefit, so a nested directive is a build error.
 *
 * @param {string} key      key of the template being expanded (for error text)
 * @param {string} content  raw template source
 * @param {(partialKey: string) => string|undefined} resolve  partial lookup
 * @returns {string} content with every directive replaced
 */
export function expandIncludes(key, content, resolve) {
  return content.replace(INCLUDE_RE, (_match, indent, partialKey) => {
    const partial = resolve(partialKey);
    if (partial === undefined) {
      throw new Error(`Template ${key} includes unknown partial ${partialKey}`);
    }
    if (HAS_INCLUDE_RE.test(partial)) {
      throw new Error(`Partial ${partialKey} contains a nested @include — not supported`);
    }
    // Drop the partial's own header comment: it documents the file, and
    // shipping it into every host template would repeat it once per include.
    const body = partial.replace(LEADING_COMMENT_RE, '');
    // Re-indent so the inlined block keeps the host template's shape.
    return body.trim().split('\n').map((line) => indent + line).join('\n');
  });
}

/** Recursively list *.html under a dir. */
function htmlFiles(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...htmlFiles(p));
    else if (name.endsWith('.html')) out.push(p);
  }
  return out;
}

/** Guard: templates must contain no <script> and no inline on*= handlers. */
export function validateTemplate(key, content) {
  if (/<script\b/i.test(content)) throw new Error(`Template ${key} contains a <script> tag`);
  if (/\s+on[a-z]+\s*=/i.test(content)) throw new Error(`Template ${key} contains an inline on* handler`);
  return true;
}

/** Build the inlined <template> block from {key, content} records. */
export function buildTemplateBlock(records) {
  const partials = new Map(
    records.filter((r) => isPartial(r.key)).map((r) => [r.key, r.content]),
  );
  const parts = records
    .filter((r) => !isPartial(r.key))
    .slice()
    .sort((a, b) => a.key.localeCompare(b.key))
    .map(({ key, content }) => {
      const expanded = expandIncludes(key, content, (k) => partials.get(k));
      validateTemplate(key, expanded);
      return `<template data-tpl="${key}">${expanded.trim()}</template>`;
    });
  return [START, ...parts, END].join('\n');
}

/**
 * Collect template records from the app js/ tree.
 * @param {string} [dir] App-Wurzel (Standard: dieses Repo)
 * @returns {{key: string, content: string}[]}
 */
function collect(dir = APP_DIR) {
  return htmlFiles(join(dir, KEY_PREFIX)).map(abs => ({
    key: relative(dir, abs).split('\\').join('/'),
    content: readFileSync(abs, 'utf8'),
  }));
}

/** Replace the marker region in a .dist source with `block`. */
function splice(name, html, block) {
  const s = html.indexOf(START);
  const e = html.indexOf(END);
  if (s === -1 || e === -1) {
    throw new Error(`${name} is missing TEMPLATES:START/END markers`);
  }
  return html.slice(0, s) + block + html.slice(e + END.length);
}

// The web entry (index.dist.html) is the only committed .dist source; index.html
// is generated from it and gitignored (rebuilt here).
const TARGETS = [
  { dist: 'index.dist.html', out: 'index.html' },
];

/**
 * Die fertige index.html als String — Template-Block in index.dist.html
 * gespliced, ohne irgendetwas zu schreiben.
 *
 * runBuild() nutzt das, damit index.html EINMAL am Ende geschrieben wird.
 * Vorher schrieb dieser Schritt die Datei sofort im Dev-Entry-Zustand
 * (Script-Tag auf js/app.js) und ein parallel laufender Testlauf sah eine
 * tote App-Shell.
 *
 * @param {string} [dir] App-Wurzel (Standard: dieses Repo)
 * @returns {string} vollständige index.html
 */
export function renderIndexHtml(dir = APP_DIR) {
  const block = buildTemplateBlock(collect(dir));
  const distPath = join(dir, 'index.dist.html');
  return splice('index.dist.html', readFileSync(distPath, 'utf8'), block);
}

function main() {
  const check = process.argv.includes('--check');
  const block = buildTemplateBlock(collect());
  let stale = false;
  for (const { dist, out } of TARGETS) {
    const distPath = join(APP_DIR, dist);
    if (!existsSync(distPath)) continue;          // shell absent → skip
    const outPath = join(APP_DIR, out);
    const next = splice(dist, readFileSync(distPath, 'utf8'), block);
    if (check) {
      const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : null;
      if (current !== next) {
        console.error(`${out} is STALE — run: node tools/build-templates/build.mjs`);
        stale = true;
      }
    } else {
      writeFileSync(outPath, next);
      console.log(`build-templates: ${out} written from ${dist}`);
    }
  }
  if (check) {
    if (stale) process.exit(1);
    console.log('build-templates: all targets up to date');
  }
}

// Nur als CLI ausführen — nicht, wenn eine andere build.mjs dieses Modul
// importiert (ein endsWith('build.mjs')-Test würde dort mitfeuern).
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
