#!/usr/bin/env node
/**
 * build-templates — inline every js/ ** / *.html template into index.html as
 * <template data-tpl="<relpath>"> blocks, so the engine can clone() them
 * (sink-free) instead of fetch()+DOMParser. Zero dependencies.
 *
 *   node tools/build-templates/build.mjs           # rewrite index.html in place
 *   node tools/build-templates/build.mjs --check   # exit 1 if index.html stale
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { readdirSync, statSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const APP_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
export const KEY_PREFIX = 'js/';
const START = '<!-- TEMPLATES:START (generated by tools/build-templates) -->';
const END = '<!-- TEMPLATES:END -->';

/** Recursively list *.html under a dir. */
function htmlFiles(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...htmlFiles(p));
    else if (name.endsWith('.html')) out.push(p);
  }
  return out;
}

/** Guard: templates must contain no <script> and no inline on*= handlers. */
export function validateTemplate(key, content) {
  if (/<script\b/i.test(content)) throw new Error(`Template ${key} contains a <script> tag`);
  if (/\s+on[a-z]+\s*=/i.test(content)) throw new Error(`Template ${key} contains an inline on* handler`);
  return true;
}

/** Build the inlined <template> block from {key, content} records. */
export function buildTemplateBlock(records) {
  const parts = records
    .slice()
    .sort((a, b) => a.key.localeCompare(b.key))
    .map(({ key, content }) => {
      validateTemplate(key, content);
      return `<template data-tpl="${key}">${content.trim()}</template>`;
    });
  return [START, ...parts, END].join('\n');
}

/** Collect template records from the app js/ tree. */
function collect() {
  return htmlFiles(join(APP_DIR, KEY_PREFIX)).map(abs => ({
    key: relative(APP_DIR, abs).split('\\').join('/'),
    content: readFileSync(abs, 'utf8'),
  }));
}

/** Replace the marker region in a .dist source with `block`. */
function splice(name, html, block) {
  const s = html.indexOf(START);
  const e = html.indexOf(END);
  if (s === -1 || e === -1) {
    throw new Error(`${name} is missing TEMPLATES:START/END markers`);
  }
  return html.slice(0, s) + block + html.slice(e + END.length);
}

// The web entry (index.dist.html) is the only committed .dist source; index.html
// is generated from it and gitignored (rebuilt here).
const TARGETS = [
  { dist: 'index.dist.html', out: 'index.html' },
];

function main() {
  const check = process.argv.includes('--check');
  const block = buildTemplateBlock(collect());
  let stale = false;
  for (const { dist, out } of TARGETS) {
    const distPath = join(APP_DIR, dist);
    if (!existsSync(distPath)) continue;          // shell absent → skip
    const outPath = join(APP_DIR, out);
    const next = splice(dist, readFileSync(distPath, 'utf8'), block);
    if (check) {
      const current = existsSync(outPath) ? readFileSync(outPath, 'utf8') : null;
      if (current !== next) {
        console.error(`${out} is STALE — run: node tools/build-templates/build.mjs`);
        stale = true;
      }
    } else {
      writeFileSync(outPath, next);
      console.log(`build-templates: ${out} written from ${dist}`);
    }
  }
  if (check) {
    if (stale) process.exit(1);
    console.log('build-templates: all targets up to date');
  }
}

if (process.argv[1] && process.argv[1].endsWith('build.mjs')) main();
